# Generated by Django 5.1.15 on 2026-07-23 12:03

import cases.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import connection, migrations, models


def add_partial_unique_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "CREATE UNIQUE INDEX one_problem_flight_per_case "
        "ON cases_flightsegment (case_id) WHERE is_problem_flight;"
    )


def drop_partial_unique_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS one_problem_flight_per_case;")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VALID', 'Valid'), ('ASSIGNED', 'Assigned'), ('INVALID', 'Invalid')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^\\+?[0-9\\s\\-()]{7,30}$')])),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('reservation_number', models.CharField(max_length=30)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('gdpr_consent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BOARDING_PASS', 'Boarding pass'), ('ID_DOCUMENT', 'ID / Passport')], max_length=20)),
                ('file', models.FileField(upload_to=cases.models.case_document_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=80)),
                ('size_bytes', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'kind'), name='uniq_case_document_kind')],
            },
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('flight_date', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=80)),
                ('planned_departure_time', models.DateTimeField()),
                ('planned_arrival_time', models.DateTimeField()),
                ('is_problem_flight', models.BooleanField(default=False)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='airports.airport')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='cases.case')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='airports.airport')),
            ],
            options={
                'ordering': ['case', 'order'],
                'constraints': [models.UniqueConstraint(fields=('case', 'order'), name='uniq_case_segment_order'), models.CheckConstraint(condition=models.Q(('order__lte', 4)), name='segment_order_max_4')],
            },
        ),
        migrations.RunPython(add_partial_unique_index, drop_partial_unique_index),
    ]
