# Generated by Django 5.1.15 on 2026-07-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='compensation_amount_eur',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='compensation_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('compensation_amount_eur__isnull', True), ('compensation_amount_eur__in', [250, 400, 600]), _connector='OR'), name='compensation_amount_eur_valid'),
        ),
    ]
