# Generated by Django 5.x for CASE_03 disruption fields.
from django.db import migrations, models


BACKFILL_DESCRIPTION = (
    "(migrated from CASE_01/CASE_02; no disruption info collected)"
)

DISRUPTION_TYPE_CHOICES = [
    ("CANCELLATION", "Cancellation"),
    ("DELAY", "Delay"),
    ("DENIED_BOARDING", "Denied boarding"),
    ("UNSPECIFIED", "Unspecified (legacy)"),
]

CANCELLATION_NOTICE_CHOICES = [
    ("MORE_THAN_14_DAYS", "More than 14 days before"),
    ("LESS_THAN_14_DAYS", "Less than 14 days before"),
    ("ON_FLIGHT_DAY", "On the flight day"),
]

DELAY_DURATION_CHOICES = [
    ("LESS_THAN_3H", "Less than 3 hours"),
    ("MORE_THAN_3H", "More than 3 hours"),
    ("CONNECTION_LOST", "Connection flight lost"),
]

DENIED_BOARDING_REASON_CHOICES = [
    ("OVERBOOKED", "Flight overbooked"),
    ("AGGRESSIVE_BEHAVIOR", "Aggressive behaviour with staff"),
    ("INTOXICATION", "Intoxication"),
    ("UNSPECIFIED", "Unspecified reason"),
]

MOTIVE_MENTIONED_CHOICES = [
    ("YES", "Yes"),
    ("NO", "No"),
    ("DONT_KNOW", "I don't know"),
]

AIRLINE_MOTIVE_CHOICES = [
    ("TECHNICAL", "Technical problem"),
    ("WEATHER", "Meteorological conditions"),
    ("STRIKE", "Strike"),
    ("AIRPORT_ISSUE", "Problems with airport"),
    ("CREW", "Crew problems"),
    ("OTHER", "Other motives"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_compensation_fields"),
    ]

    operations = [
        # 1. Two NOT NULL columns with a temporary default to backfill existing rows.
        migrations.AddField(
            model_name="case",
            name="disruption_type",
            field=models.CharField(
                max_length=20,
                choices=DISRUPTION_TYPE_CHOICES,
                default="UNSPECIFIED",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="incident_description",
            field=models.TextField(
                max_length=2000,
                default=BACKFILL_DESCRIPTION,
            ),
            preserve_default=False,
        ),
        # 2. Six nullable columns — no backfill needed.
        migrations.AddField(
            model_name="case",
            name="cancellation_notice",
            field=models.CharField(
                max_length=20, choices=CANCELLATION_NOTICE_CHOICES,
                null=True, blank=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="delay_duration",
            field=models.CharField(
                max_length=20, choices=DELAY_DURATION_CHOICES,
                null=True, blank=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="denied_boarding_voluntary",
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="case",
            name="denied_boarding_reason",
            field=models.CharField(
                max_length=30, choices=DENIED_BOARDING_REASON_CHOICES,
                null=True, blank=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="airline_motive_mentioned",
            field=models.CharField(
                max_length=10, choices=MOTIVE_MENTIONED_CHOICES,
                null=True, blank=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="airline_motive",
            field=models.CharField(
                max_length=20, choices=AIRLINE_MOTIVE_CHOICES,
                null=True, blank=True,
            ),
        ),
        # 3. Add the check constraint (allows the UNSPECIFIED sentinel too).
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                check=models.Q(disruption_type__in=[
                    "CANCELLATION", "DELAY", "DENIED_BOARDING", "UNSPECIFIED",
                ]),
                name="disruption_type_valid",
            ),
        ),
    ]
